[package]
name = "hypergl_core"
version = "0.1.0"
authors = ["laopo001 <353272497@qq.com>"]
edition = "2018"

[dependencies]
glow = { git = 'https://github.com/grovesNL/glow.git' }

[target.'cfg(not(any(target_arch = "wasm32")))'.dependencies]
glutin = "0.19.0"